# List Built-in functions
data = [10,20,30,30,40,50]
print(len(data))
print(data.count(30))
print(data.index(30))
data.append(70)
print(data)
data.insert(3,69)
print(data)
data.pop()
print(data)
data.pop(5)
print(data)
print(sum(data))
print(max(data))
print(min(data))
